# Python CircleCI 2.0 configuration file
version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.7

    environment:
      DEEPSOURCE_DSN: https://bf6e178c82fa4c409794ef9243c48ef5@deepsource.io

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install deps
          command: pip install -r requirements.txt --user

      - run:
          name: current commit
          command: echo $CIRCLE_SHA1

      - run:
          name: run tests
          command: make test

      - run:
          name: Report results to DeepSource
          command: |
            # Install DeepSource CLI
            curl https://deepsource.io/cli | sh
            # Report coverage artifact to the 'test-coverage' analyzer
            ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml


workflows:
  version: 2
  test:
    jobs:
      - test
